flowable:
  cmmn:
    async:
      executor:
        default-async-job-acquire-wait-time-in-millis: 5000
        default-timer-job-acquire-wait-time-in-millis: 5000
  common:
    app:
      idm-admin:
        password: test
        user: admin
      idm-url: http://localhost:8080/flowable-idm
      role-prefix: ''
  content:
    storage:
      create-root: true
      root-folder: data/
  experimental:
    debugger:
      enabled: false
  form-field-validation-enabled: false
  process:
    async:
      executor:
        default-async-job-acquire-wait-time-in-millis: 5000
        default-timer-job-acquire-wait-time-in-millis: 5000
    definition-cache-limit: 512
  rest:
    app:
      authentication-mode: verify-privilege
  task:
    app:
      rest-enabled: true
management:
  endpoint:
    health:
      roles: access-admin
      show-details: when_authorized
  endpoints:
    jmx:
      unique-names: true
    web:
      exposure:
        include: '*'
server:
  port: 8080
  servlet:
    context-path: /flowable-task
spring:
  aop:
    auto: false
    proxy-target-class: false
  application:
    name: flowable-ui-task
  banner:
    location: classpath:/org/flowable/spring/boot/flowable-banner.txt
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bpm?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    password: bpm
    username: bpm
    hikari:
      idleTimeout: 300000
      maxLifetime: 600000
      maximumPoolSize: 50
      minimumIdle: 10
      poolName: ${spring.application.name}
  jmx:
    default-domain: ${spring.application.name}
  security:
    filter:
      dispatcher-types: REQUEST,FORWARD,ASYNC
  servlet:
    multipart:
      max-file-size: 10MB
  task:
    execution:
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
      thread-name-prefix: flowable-task-Executor-
    scheduling:
      pool:
        size: 5
